// 本地兜底模板数据（6个热门城市）
// 当腾讯 LBS API 失败时使用

const FALLBACK_DATA = {
  上海: {
    亲子遛娃: [
      {
        name: "上海迪士尼乐园",
        address: "浦东新区川沙新镇黄赵路310号",
        category: "主题乐园",
        duration: 8,
        cost: 500,
      },
      {
        name: "上海海昌海洋公园",
        address: "浦东新区银飞路166号",
        category: "海洋馆",
        duration: 6,
        cost: 300,
      },
      {
        name: "上海自然博物馆",
        address: "静安区北京西路510号",
        category: "博物馆",
        duration: 4,
        cost: 30,
      },
      {
        name: "上海科技馆",
        address: "浦东新区世纪大道2000号",
        category: "科技馆",
        duration: 5,
        cost: 60,
      },
      {
        name: "上海野生动物园",
        address: "浦东新区南六公路178号",
        category: "动物园",
        duration: 6,
        cost: 130,
      },
      {
        name: "世纪公园",
        address: "浦东新区锦绣路1001号",
        category: "公园",
        duration: 3,
        cost: 10,
      },
      {
        name: "上海欢乐谷",
        address: "松江区林湖路888号",
        category: "主题乐园",
        duration: 7,
        cost: 280,
      },
      {
        name: "上海海洋水族馆",
        address: "浦东新区陆家嘴环路1388号",
        category: "水族馆",
        duration: 3,
        cost: 160,
      },
    ],
    情侣约会: [
      {
        name: "外滩",
        address: "黄浦区中山东一路",
        category: "地标景点",
        duration: 2,
        cost: 0,
      },
      {
        name: "东方明珠",
        address: "浦东新区陆家嘴世纪大道1号",
        category: "观景台",
        duration: 3,
        cost: 180,
      },
      {
        name: "田子坊",
        address: "黄浦区泰康路210弄",
        category: "文艺街区",
        duration: 2,
        cost: 100,
      },
      {
        name: "新天地",
        address: "黄浦区太仓路181弄",
        category: "时尚街区",
        duration: 3,
        cost: 200,
      },
      {
        name: "思南公馆",
        address: "黄浦区思南路",
        category: "历史建筑",
        duration: 2,
        cost: 50,
      },
      {
        name: "武康路",
        address: "徐汇区武康路",
        category: "历史街区",
        duration: 2,
        cost: 50,
      },
      {
        name: "上海中心大厦",
        address: "浦东新区陆家嘴银城中路501号",
        category: "观景台",
        duration: 2,
        cost: 180,
      },
      {
        name: "豫园",
        address: "黄浦区安仁街137号",
        category: "古典园林",
        duration: 3,
        cost: 40,
      },
    ],
    朋友小聚: [
      {
        name: "南京路步行街",
        address: "黄浦区南京东路",
        category: "商业街",
        duration: 3,
        cost: 150,
      },
      {
        name: "田子坊",
        address: "黄浦区泰康路210弄",
        category: "文艺街区",
        duration: 2,
        cost: 100,
      },
      {
        name: "M50创意园",
        address: "普陀区莫干山路50号",
        category: "艺术园区",
        duration: 2,
        cost: 30,
      },
      {
        name: "新天地",
        address: "黄浦区太仓路181弄",
        category: "时尚街区",
        duration: 3,
        cost: 200,
      },
      {
        name: "上海博物馆",
        address: "黄浦区人民大道201号",
        category: "博物馆",
        duration: 3,
        cost: 0,
      },
      {
        name: "上海当代艺术博物馆",
        address: "黄浦区花园港路200号",
        category: "博物馆",
        duration: 3,
        cost: 0,
      },
      {
        name: "朱家角古镇",
        address: "青浦区朱家角镇",
        category: "古镇",
        duration: 4,
        cost: 80,
      },
      {
        name: "上海杜莎夫人蜡像馆",
        address: "黄浦区南京西路2-68号新世界城10楼",
        category: "展馆",
        duration: 2,
        cost: 150,
      },
    ],
    美食探店: [
      {
        name: "鼎泰丰(新天地店)",
        address: "黄浦区马当路245号",
        category: "餐厅",
        duration: 2,
        cost: 150,
      },
      {
        name: "豫园",
        address: "黄浦区安仁街137号",
        category: "美食街",
        duration: 3,
        cost: 100,
      },
      {
        name: "新天地",
        address: "黄浦区太仓路181弄",
        category: "美食街区",
        duration: 3,
        cost: 200,
      },
      {
        name: "田子坊",
        address: "黄浦区泰康路210弄",
        category: "美食街区",
        duration: 2,
        cost: 100,
      },
      {
        name: "南京路步行街",
        address: "黄浦区南京东路",
        category: "商业街",
        duration: 3,
        cost: 150,
      },
      {
        name: "城隍庙",
        address: "黄浦区方浜中路249号",
        category: "美食街",
        duration: 2,
        cost: 80,
      },
      {
        name: "外滩源",
        address: "黄浦区中山东一路",
        category: "美食街区",
        duration: 2,
        cost: 200,
      },
      {
        name: "思南公馆",
        address: "黄浦区思南路",
        category: "美食街区",
        duration: 2,
        cost: 150,
      },
    ],
  },

  北京: {
    亲子遛娃: [
      {
        name: "北京环球影城",
        address: "通州区京哈高速与东六环路交汇处",
        category: "主题乐园",
        duration: 8,
        cost: 600,
      },
      {
        name: "北京动物园",
        address: "西城区西直门外大街137号",
        category: "动物园",
        duration: 5,
        cost: 20,
      },
      {
        name: "中国科技馆",
        address: "朝阳区北辰东路5号",
        category: "科技馆",
        duration: 4,
        cost: 30,
      },
      {
        name: "北京海洋馆",
        address: "海淀区高梁桥斜街乙18号",
        category: "海洋馆",
        duration: 3,
        cost: 160,
      },
      {
        name: "故宫博物院",
        address: "东城区景山前街4号",
        category: "博物馆",
        duration: 5,
        cost: 60,
      },
      {
        name: "颐和园",
        address: "海淀区新建宫门路19号",
        category: "公园",
        duration: 4,
        cost: 30,
      },
      {
        name: "天坛公园",
        address: "东城区天坛东里甲1号",
        category: "公园",
        duration: 3,
        cost: 15,
      },
      {
        name: "北京欢乐谷",
        address: "朝阳区东四环小武基北路",
        category: "主题乐园",
        duration: 7,
        cost: 280,
      },
    ],
    情侣约会: [
      {
        name: "故宫博物院",
        address: "东城区景山前街4号",
        category: "历史建筑",
        duration: 5,
        cost: 60,
      },
      {
        name: "颐和园",
        address: "海淀区新建宫门路19号",
        category: "园林",
        duration: 4,
        cost: 30,
      },
      {
        name: "什刹海",
        address: "西城区羊房胡同",
        category: "景区",
        duration: 3,
        cost: 0,
      },
      {
        name: "南锣鼓巷",
        address: "东城区南锣鼓巷",
        category: "历史街区",
        duration: 2,
        cost: 50,
      },
      {
        name: "798艺术区",
        address: "朝阳区酒仙桥路4号",
        category: "艺术园区",
        duration: 3,
        cost: 0,
      },
      {
        name: "三里屯",
        address: "朝阳区三里屯路",
        category: "商业街区",
        duration: 3,
        cost: 200,
      },
      {
        name: "鸟巢水立方",
        address: "朝阳区国家体育场南路1号",
        category: "地标建筑",
        duration: 2,
        cost: 50,
      },
      {
        name: "景山公园",
        address: "西城区景山西街44号",
        category: "公园",
        duration: 2,
        cost: 2,
      },
    ],
    朋友小聚: [
      {
        name: "798艺术区",
        address: "朝阳区酒仙桥路4号",
        category: "艺术园区",
        duration: 3,
        cost: 50,
      },
      {
        name: "三里屯",
        address: "朝阳区三里屯路",
        category: "商业街区",
        duration: 3,
        cost: 200,
      },
      {
        name: "南锣鼓巷",
        address: "东城区南锣鼓巷",
        category: "历史街区",
        duration: 2,
        cost: 80,
      },
      {
        name: "什刹海",
        address: "西城区羊房胡同",
        category: "景区",
        duration: 3,
        cost: 100,
      },
      {
        name: "王府井",
        address: "东城区王府井大街",
        category: "商业街",
        duration: 3,
        cost: 150,
      },
      {
        name: "国家博物馆",
        address: "东城区东长安街16号",
        category: "博物馆",
        duration: 3,
        cost: 0,
      },
      {
        name: "后海酒吧街",
        address: "西城区什刹海",
        category: "酒吧街",
        duration: 3,
        cost: 200,
      },
      {
        name: "五道营胡同",
        address: "东城区安定门内大街",
        category: "文艺街区",
        duration: 2,
        cost: 80,
      },
    ],
    美食探店: [
      {
        name: "全聚德(前门店)",
        address: "东城区前门大街30号",
        category: "餐厅",
        duration: 2,
        cost: 200,
      },
      {
        name: "簋街",
        address: "东城区东直门内大街",
        category: "美食街",
        duration: 3,
        cost: 150,
      },
      {
        name: "王府井小吃街",
        address: "东城区王府井大街",
        category: "美食街",
        duration: 2,
        cost: 100,
      },
      {
        name: "护国寺小吃",
        address: "西城区护国寺大街",
        category: "小吃店",
        duration: 2,
        cost: 50,
      },
      {
        name: "南锣鼓巷",
        address: "东城区南锣鼓巷",
        category: "美食街区",
        duration: 2,
        cost: 100,
      },
      {
        name: "三里屯",
        address: "朝阳区三里屯路",
        category: "美食街区",
        duration: 3,
        cost: 200,
      },
      {
        name: "什刹海",
        address: "西城区羊房胡同",
        category: "美食街区",
        duration: 3,
        cost: 150,
      },
      {
        name: "牛街",
        address: "西城区牛街",
        category: "美食街",
        duration: 2,
        cost: 80,
      },
    ],
  },

  广州: {
    亲子遛娃: [
      {
        name: "长隆欢乐世界",
        address: "番禺区汉溪大道东与长隆地铁大道交汇处",
        category: "主题乐园",
        duration: 8,
        cost: 280,
      },
      {
        name: "长隆野生动物世界",
        address: "番禺区大石镇105国道大石段593号",
        category: "动物园",
        duration: 6,
        cost: 300,
      },
      {
        name: "广州海洋馆",
        address: "越秀区先烈中路120号",
        category: "海洋馆",
        duration: 3,
        cost: 150,
      },
      {
        name: "广东科学中心",
        address: "番禺区大学城西六路168号",
        category: "科技馆",
        duration: 4,
        cost: 60,
      },
      {
        name: "白云山",
        address: "白云区广园中路801号",
        category: "公园",
        duration: 4,
        cost: 5,
      },
      {
        name: "越秀公园",
        address: "越秀区解放北路988号",
        category: "公园",
        duration: 3,
        cost: 0,
      },
      {
        name: "广州塔",
        address: "海珠区阅江西路222号",
        category: "地标建筑",
        duration: 3,
        cost: 150,
      },
      {
        name: "珠江夜游",
        address: "海珠区滨江东路",
        category: "游船",
        duration: 2,
        cost: 80,
      },
    ],
    情侣约会: [
      {
        name: "广州塔",
        address: "海珠区阅江西路222号",
        category: "地标建筑",
        duration: 3,
        cost: 150,
      },
      {
        name: "珠江夜游",
        address: "海珠区滨江东路",
        category: "游船",
        duration: 2,
        cost: 80,
      },
      {
        name: "沙面",
        address: "荔湾区沙面大街",
        category: "历史街区",
        duration: 2,
        cost: 0,
      },
      {
        name: "二沙岛",
        address: "越秀区二沙岛",
        category: "景区",
        duration: 2,
        cost: 0,
      },
      {
        name: "太古仓",
        address: "海珠区革新路124号",
        category: "文艺街区",
        duration: 2,
        cost: 100,
      },
      {
        name: "红专厂",
        address: "天河区员村四横路128号",
        category: "艺术园区",
        duration: 2,
        cost: 0,
      },
      {
        name: "花城广场",
        address: "天河区花城广场",
        category: "城市广场",
        duration: 2,
        cost: 0,
      },
      {
        name: "白云山",
        address: "白云区广园中路801号",
        category: "公园",
        duration: 4,
        cost: 5,
      },
    ],
    朋友小聚: [
      {
        name: "北京路步行街",
        address: "越秀区北京路",
        category: "商业街",
        duration: 3,
        cost: 150,
      },
      {
        name: "上下九步行街",
        address: "荔湾区上下九路",
        category: "商业街",
        duration: 3,
        cost: 100,
      },
      {
        name: "太古仓",
        address: "海珠区革新路124号",
        category: "文艺街区",
        duration: 2,
        cost: 100,
      },
      {
        name: "红专厂",
        address: "天河区员村四横路128号",
        category: "艺术园区",
        duration: 2,
        cost: 50,
      },
      {
        name: "天河城",
        address: "天河区天河路208号",
        category: "购物中心",
        duration: 3,
        cost: 200,
      },
      {
        name: "珠江新城",
        address: "天河区珠江新城",
        category: "商业区",
        duration: 3,
        cost: 200,
      },
      {
        name: "沙面",
        address: "荔湾区沙面大街",
        category: "历史街区",
        duration: 2,
        cost: 50,
      },
      {
        name: "陈家祠",
        address: "荔湾区中山七路恩龙里34号",
        category: "历史建筑",
        duration: 2,
        cost: 10,
      },
    ],
    美食探店: [
      {
        name: "上下九步行街",
        address: "荔湾区上下九路",
        category: "美食街",
        duration: 3,
        cost: 100,
      },
      {
        name: "北京路步行街",
        address: "越秀区北京路",
        category: "美食街",
        duration: 3,
        cost: 150,
      },
      {
        name: "惠福东路美食街",
        address: "越秀区惠福东路",
        category: "美食街",
        duration: 2,
        cost: 80,
      },
      {
        name: "西华路",
        address: "荔湾区西华路",
        category: "美食街",
        duration: 2,
        cost: 60,
      },
      {
        name: "太古仓",
        address: "海珠区革新路124号",
        category: "美食街区",
        duration: 2,
        cost: 150,
      },
      {
        name: "珠江新城",
        address: "天河区珠江新城",
        category: "美食街区",
        duration: 3,
        cost: 200,
      },
      {
        name: "天河城",
        address: "天河区天河路208号",
        category: "美食街区",
        duration: 3,
        cost: 200,
      },
      {
        name: "沙面",
        address: "荔湾区沙面大街",
        category: "美食街区",
        duration: 2,
        cost: 100,
      },
    ],
  },

  杭州: {
    亲子遛娃: [
      {
        name: "杭州乐园",
        address: "萧山区风情大道2555号",
        category: "主题乐园",
        duration: 7,
        cost: 230,
      },
      {
        name: "杭州极地海洋公园",
        address: "萧山区湘湖路777号",
        category: "海洋馆",
        duration: 4,
        cost: 220,
      },
      {
        name: "浙江自然博物馆",
        address: "西湖区天目山路160号",
        category: "博物馆",
        duration: 3,
        cost: 0,
      },
      {
        name: "杭州动物园",
        address: "西湖区虎跑路40号",
        category: "动物园",
        duration: 4,
        cost: 20,
      },
      {
        name: "西湖",
        address: "西湖区龙井路1号",
        category: "景区",
        duration: 5,
        cost: 0,
      },
      {
        name: "宋城",
        address: "西湖区之江路148号",
        category: "主题公园",
        duration: 5,
        cost: 310,
      },
      {
        name: "浙江科技馆",
        address: "西湖区西溪路550号",
        category: "科技馆",
        duration: 3,
        cost: 30,
      },
      {
        name: "西溪湿地",
        address: "西湖区天目山路518号",
        category: "湿地公园",
        duration: 4,
        cost: 80,
      },
    ],
    情侣约会: [
      {
        name: "西湖",
        address: "西湖区龙井路1号",
        category: "景区",
        duration: 5,
        cost: 0,
      },
      {
        name: "灵隐寺",
        address: "西湖区灵隐路法云弄1号",
        category: "寺庙",
        duration: 3,
        cost: 45,
      },
      {
        name: "雷峰塔",
        address: "西湖区南山路15号",
        category: "古塔",
        duration: 2,
        cost: 40,
      },
      {
        name: "河坊街",
        address: "上城区河坊街",
        category: "历史街区",
        duration: 2,
        cost: 50,
      },
      {
        name: "西溪湿地",
        address: "西湖区天目山路518号",
        category: "湿地公园",
        duration: 4,
        cost: 80,
      },
      {
        name: "钱塘江",
        address: "滨江区钱塘江边",
        category: "江景",
        duration: 2,
        cost: 0,
      },
      {
        name: "南宋御街",
        address: "上城区中山中路",
        category: "历史街区",
        duration: 2,
        cost: 50,
      },
      {
        name: "太子湾公园",
        address: "西湖区南山路5-1号",
        category: "公园",
        duration: 2,
        cost: 0,
      },
    ],
    朋友小聚: [
      {
        name: "河坊街",
        address: "上城区河坊街",
        category: "历史街区",
        duration: 2,
        cost: 100,
      },
      {
        name: "南宋御街",
        address: "上城区中山中路",
        category: "历史街区",
        duration: 2,
        cost: 80,
      },
      {
        name: "湖滨银泰",
        address: "上城区延安路98号",
        category: "购物中心",
        duration: 3,
        cost: 200,
      },
      {
        name: "西湖天地",
        address: "上城区南山路147号",
        category: "商业街区",
        duration: 2,
        cost: 150,
      },
      {
        name: "运河",
        address: "拱墅区运河广场",
        category: "景区",
        duration: 3,
        cost: 0,
      },
      {
        name: "浙江美术馆",
        address: "西湖区南山路138号",
        category: "美术馆",
        duration: 2,
        cost: 0,
      },
      {
        name: "中国美术学院",
        address: "西湖区南山路218号",
        category: "艺术园区",
        duration: 2,
        cost: 0,
      },
      {
        name: "西溪湿地",
        address: "西湖区天目山路518号",
        category: "湿地公园",
        duration: 4,
        cost: 80,
      },
    ],
    美食探店: [
      {
        name: "河坊街",
        address: "上城区河坊街",
        category: "美食街",
        duration: 2,
        cost: 100,
      },
      {
        name: "南宋御街",
        address: "上城区中山中路",
        category: "美食街",
        duration: 2,
        cost: 80,
      },
      {
        name: "湖滨银泰",
        address: "上城区延安路98号",
        category: "美食街区",
        duration: 3,
        cost: 200,
      },
      {
        name: "西湖天地",
        address: "上城区南山路147号",
        category: "美食街区",
        duration: 2,
        cost: 150,
      },
      {
        name: "胜利河美食街",
        address: "拱墅区胜利河",
        category: "美食街",
        duration: 2,
        cost: 80,
      },
      {
        name: "吴山夜市",
        address: "上城区吴山广场",
        category: "夜市",
        duration: 2,
        cost: 60,
      },
      {
        name: "知味观",
        address: "上城区仁和路83号",
        category: "餐厅",
        duration: 2,
        cost: 100,
      },
      {
        name: "外婆家",
        address: "西湖区马塍路2号",
        category: "餐厅",
        duration: 2,
        cost: 80,
      },
    ],
  },

  成都: {
    亲子遛娃: [
      {
        name: "成都大熊猫繁育研究基地",
        address: "成华区外北熊猫大道1375号",
        category: "动物园",
        duration: 4,
        cost: 58,
      },
      {
        name: "成都欢乐谷",
        address: "金牛区西华大道16号",
        category: "主题乐园",
        duration: 7,
        cost: 230,
      },
      {
        name: "成都海昌极地海洋公园",
        address: "双流区天府大道南段1177号",
        category: "海洋馆",
        duration: 5,
        cost: 220,
      },
      {
        name: "四川科技馆",
        address: "成华区天府大道北段8号",
        category: "科技馆",
        duration: 3,
        cost: 0,
      },
      {
        name: "成都动物园",
        address: "成华区昭觉寺南路234号",
        category: "动物园",
        duration: 4,
        cost: 20,
      },
      {
        name: "浣花溪公园",
        address: "青羊区青华路9号",
        category: "公园",
        duration: 3,
        cost: 0,
      },
      {
        name: "人民公园",
        address: "青羊区少城路12号",
        category: "公园",
        duration: 2,
        cost: 0,
      },
      {
        name: "国色天乡",
        address: "温江区万春镇",
        category: "主题乐园",
        duration: 6,
        cost: 180,
      },
    ],
    情侣约会: [
      {
        name: "宽窄巷子",
        address: "青羊区金河路口宽窄巷子",
        category: "历史街区",
        duration: 3,
        cost: 100,
      },
      {
        name: "锦里",
        address: "武侯区武侯祠大街231号",
        category: "历史街区",
        duration: 2,
        cost: 50,
      },
      {
        name: "春熙路",
        address: "锦江区春熙路",
        category: "商业街",
        duration: 3,
        cost: 150,
      },
      {
        name: "太古里",
        address: "锦江区中纱帽街8号",
        category: "商业街区",
        duration: 3,
        cost: 200,
      },
      {
        name: "九眼桥",
        address: "锦江区九眼桥",
        category: "酒吧街",
        duration: 3,
        cost: 150,
      },
      {
        name: "东郊记忆",
        address: "成华区建设南路中段4号",
        category: "艺术园区",
        duration: 2,
        cost: 0,
      },
      {
        name: "浣花溪公园",
        address: "青羊区青华路9号",
        category: "公园",
        duration: 3,
        cost: 0,
      },
      {
        name: "人民公园",
        address: "青羊区少城路12号",
        category: "公园",
        duration: 2,
        cost: 0,
      },
    ],
    朋友小聚: [
      {
        name: "宽窄巷子",
        address: "青羊区金河路口宽窄巷子",
        category: "历史街区",
        duration: 3,
        cost: 100,
      },
      {
        name: "锦里",
        address: "武侯区武侯祠大街231号",
        category: "历史街区",
        duration: 2,
        cost: 80,
      },
      {
        name: "春熙路",
        address: "锦江区春熙路",
        category: "商业街",
        duration: 3,
        cost: 150,
      },
      {
        name: "太古里",
        address: "锦江区中纱帽街8号",
        category: "商业街区",
        duration: 3,
        cost: 200,
      },
      {
        name: "九眼桥",
        address: "锦江区九眼桥",
        category: "酒吧街",
        duration: 3,
        cost: 150,
      },
      {
        name: "东郊记忆",
        address: "成华区建设南路中段4号",
        category: "艺术园区",
        duration: 2,
        cost: 50,
      },
      {
        name: "IFS国际金融中心",
        address: "锦江区红星路三段1号",
        category: "购物中心",
        duration: 3,
        cost: 200,
      },
      {
        name: "武侯祠",
        address: "武侯区武侯祠大街231号",
        category: "历史建筑",
        duration: 2,
        cost: 60,
      },
    ],
    美食探店: [
      {
        name: "宽窄巷子",
        address: "青羊区金河路口宽窄巷子",
        category: "美食街",
        duration: 3,
        cost: 150,
      },
      {
        name: "锦里",
        address: "武侯区武侯祠大街231号",
        category: "美食街",
        duration: 2,
        cost: 100,
      },
      {
        name: "春熙路",
        address: "锦江区春熙路",
        category: "美食街",
        duration: 3,
        cost: 150,
      },
      {
        name: "太古里",
        address: "锦江区中纱帽街8号",
        category: "美食街区",
        duration: 3,
        cost: 200,
      },
      {
        name: "玉林路",
        address: "武侯区玉林路",
        category: "美食街",
        duration: 2,
        cost: 100,
      },
      {
        name: "建设路",
        address: "成华区建设路",
        category: "美食街",
        duration: 2,
        cost: 80,
      },
      {
        name: "奎星楼街",
        address: "青羊区奎星楼街",
        category: "美食街",
        duration: 2,
        cost: 80,
      },
      {
        name: "电子科大万人食堂",
        address: "成华区建设北路二段4号",
        category: "食堂",
        duration: 1,
        cost: 30,
      },
    ],
  },

  重庆: {
    亲子遛娃: [
      {
        name: "重庆欢乐谷",
        address: "渝北区金渝大道29号",
        category: "主题乐园",
        duration: 7,
        cost: 230,
      },
      {
        name: "重庆动物园",
        address: "九龙坡区杨家坪西郊一村1号",
        category: "动物园",
        duration: 4,
        cost: 25,
      },
      {
        name: "重庆科技馆",
        address: "江北区江北城文星门街7号",
        category: "科技馆",
        duration: 3,
        cost: 0,
      },
      {
        name: "重庆海洋探索中心",
        address: "南岸区南滨路181号",
        category: "海洋馆",
        duration: 3,
        cost: 150,
      },
      {
        name: "洪崖洞",
        address: "渝中区嘉陵江滨江路88号",
        category: "景区",
        duration: 2,
        cost: 0,
      },
      {
        name: "磁器口古镇",
        address: "沙坪坝区磁童路",
        category: "古镇",
        duration: 3,
        cost: 0,
      },
      {
        name: "南山一棵树观景台",
        address: "南岸区南山公园路",
        category: "观景台",
        duration: 2,
        cost: 30,
      },
      {
        name: "长江索道",
        address: "渝中区新华路153号",
        category: "索道",
        duration: 1,
        cost: 20,
      },
    ],
    情侣约会: [
      {
        name: "洪崖洞",
        address: "渝中区嘉陵江滨江路88号",
        category: "景区",
        duration: 2,
        cost: 0,
      },
      {
        name: "南山一棵树观景台",
        address: "南岸区南山公园路",
        category: "观景台",
        duration: 2,
        cost: 30,
      },
      {
        name: "长江索道",
        address: "渝中区新华路153号",
        category: "索道",
        duration: 1,
        cost: 20,
      },
      {
        name: "解放碑",
        address: "渝中区解放碑",
        category: "地标",
        duration: 2,
        cost: 0,
      },
      {
        name: "朝天门",
        address: "渝中区朝天门",
        category: "码头",
        duration: 2,
        cost: 0,
      },
      {
        name: "鹅岭公园",
        address: "渝中区鹅岭正街176号",
        category: "公园",
        duration: 2,
        cost: 0,
      },
      {
        name: "磁器口古镇",
        address: "沙坪坝区磁童路",
        category: "古镇",
        duration: 3,
        cost: 50,
      },
      {
        name: "南滨路",
        address: "南岸区南滨路",
        category: "江景",
        duration: 2,
        cost: 0,
      },
    ],
    朋友小聚: [
      {
        name: "解放碑",
        address: "渝中区解放碑",
        category: "商业街",
        duration: 3,
        cost: 150,
      },
      {
        name: "观音桥",
        address: "江北区观音桥",
        category: "商业街",
        duration: 3,
        cost: 150,
      },
      {
        name: "洪崖洞",
        address: "渝中区嘉陵江滨江路88号",
        category: "景区",
        duration: 2,
        cost: 50,
      },
      {
        name: "磁器口古镇",
        address: "沙坪坝区磁童路",
        category: "古镇",
        duration: 3,
        cost: 80,
      },
      {
        name: "三峡博物馆",
        address: "渝中区人民路236号",
        category: "博物馆",
        duration: 2,
        cost: 0,
      },
      {
        name: "南滨路",
        address: "南岸区南滨路",
        category: "江景",
        duration: 2,
        cost: 100,
      },
      {
        name: "鹅岭二厂",
        address: "渝中区鹅岭正街1号",
        category: "艺术园区",
        duration: 2,
        cost: 0,
      },
      {
        name: "弹子石老街",
        address: "南岸区弹子石",
        category: "历史街区",
        duration: 2,
        cost: 50,
      },
    ],
    美食探店: [
      {
        name: "解放碑",
        address: "渝中区解放碑",
        category: "美食街",
        duration: 3,
        cost: 150,
      },
      {
        name: "洪崖洞",
        address: "渝中区嘉陵江滨江路88号",
        category: "美食街",
        duration: 2,
        cost: 100,
      },
      {
        name: "磁器口古镇",
        address: "沙坪坝区磁童路",
        category: "美食街",
        duration: 3,
        cost: 100,
      },
      {
        name: "观音桥",
        address: "江北区观音桥",
        category: "美食街",
        duration: 3,
        cost: 150,
      },
      {
        name: "南滨路",
        address: "南岸区南滨路",
        category: "美食街",
        duration: 2,
        cost: 150,
      },
      {
        name: "八一路好吃街",
        address: "渝中区八一路",
        category: "美食街",
        duration: 2,
        cost: 80,
      },
      {
        name: "较场口夜市",
        address: "渝中区较场口",
        category: "夜市",
        duration: 2,
        cost: 60,
      },
      {
        name: "弹子石老街",
        address: "南岸区弹子石",
        category: "美食街",
        duration: 2,
        cost: 100,
      },
    ],
  },
};

module.exports = FALLBACK_DATA;
